### PR TITLE
Fix index theme files

### PR DESCRIPTION
**Pull request by sdwolf**
This deals with [point 1. from this post](https://forum.manjaro.org/t/xfce-power-manager-icon-missing-from-theme/9249/15?u=sdwolf).

Just one more question. `index.theme.kde` seems to be an exact copy of `index.theme`. Should it not be a symlink (no idea if it work that way)?

### CODE REVIEW

**Comment by sdwolf** [comment]
I have another branch [here](https://github.com/sdwolf/vertex-maia-icon-themes/tree/add/missing-links) that fixes some of the battery indicator icons, is there any interest for this?

/cc @philmmanjaro

**Comment by philmmanjaro** [comment]
@sdwolf: sure. Send a merge request.

**Comment by sdwolf** [comment]
Awesome, I will create it later today when I get home, I want to add a few screenshots in the description as well.

That branch also contains the changes from this one, I was waiting on feedback here before opening that PR, maybe it's easier to review them separately?

**Comment by philmmanjaro** [comment]
Ya sure, in regard of the exact same file. Maybe a symlink might work. Else simply copy it ;)

**Comment by sdwolf** [comment]
Closing this since #6 includes these changes

**Pull request closed without merging**
