### PR TITLE
Adds some of the missing battery icons

### PR DESCRIPTION
**Pull request by sdwolf**
Sorry for the late PR, I made this a while ago and I don't remember exactly from which directory I copied the files, I'l try to remove the copies and replace them with symlinks if there's no hurry.

There are still some icons that I have yet not replaced, will do so in the future with a different PR.

Here is a screenshow of how it looks now on my XFCE laptop:
screenshot_2018-01-10_00-04-55

### CODE REVIEW

**Comment by P3p1t0** [comment]
Got issue with this new battery icons in Manjaro XFCE Testing. I use the Vertex Maia icon theme (version 20180114-1). Here's a screenshot.

https://forum.manjaro.org/uploads/default/original/3X/3/1/31951574ef52104814f6a2234971fa78e74f11af.png

Reported here : https://forum.manjaro.org/t/testing-update-2018-01-14-adapta-grub-live-themes-webdad-libcdio-rebuild/38337/2

**Comment by sdwolf** [comment]
OK here is how to test out what's happening:

```bash
# First clone the repository
git clone https://github.com/manjaro/vertex-maia-icon-themes.git

# Then checkout the commit before this PR
git checkout 2b2469e5cec1c850a982f6ae1253d6d4b74e4369

# Quit the current `xfce4-power-manager` session
xfce4-power-manager -q

# Use these commands below to overwrite the icon files and start the power manager in debug mode:
sudo rm -rf /usr/share/icons/Vertex-Maia/ 

# In this case the `vertex-maia-icon-themes` is the repository. 
# Change the path as you see apropriate!
sudo cp -r ~/vertex-maia-icon-themes/Vertex-Maia/ /usr/share/icons/ 

sudo gtk-update-icon-cache /usr/share/icons/Vertex-Maia 
xfce4-power-manager --debug
```

If this fixes your problem then this PR introduced a regression. Post a screenshot of the icon it displays before this PR and I might be able to figure out what is going on. A copy of the debug info from `xfce4-power-manager` will also help since it logs which icons it searches for.

**Comment by P3p1t0** [comment]
Those steps returned my situation as it was before the update.
before-steps
after-steps

Here's the output of xfce4-power-manager --debug.
[https://zerobin.net/?be22d866fe2c6468#AyxT1/tupKIujnUZRbB9W6lwaUO/JIW3ZB+dx2VB47c=](zerobin)

**Comment by sdwolf** [comment]
From that I understand, this line:
```
TRACE[xfpm-power-common.c:190] get_device_icon_name(): icon_suffix -symbolic, icon_base_length 15, upower_icon battery-missing-symbolic
```
The problem is with the icon for battery missing. That's weird, I did not touch that icon. 

Maybe commit 8409594ddf50e244199be277b99b1c191d480046 messed it up. Here's an experiment I would like you to try:

```
git checkout master
git revert 8409594ddf50e244199be277b99b1c191d480046
```

Save and exit the text editor and ovewrite the icons again:

```
sudo rm -rf /usr/share/icons/Vertex-Maia/ 
sudo cp -r ~/vertex-maia-icon-themes/Vertex-Maia/ /usr/share/icons/ 
sudo gtk-update-icon-cache /usr/share/icons/Vertex-Maia 
xfce4-power-manager --debug
```

Let me know if this time the icons are what they should be...

**Comment by P3p1t0** [comment]
Reverting commit 8409594... did not solve the initial issue; I have the new tray icon, but it's still buggy.
after-revert-8409594
Here's the output of xfce4-power-manager --debug.

[https://zerobin.net/?5062858766d03569#g2+tuEhxU8ANJbWB5s12Bw8DjRbHVtmc45lNNlD6XPI=](https://zerobin.net/?5062858766d03569#g2+tuEhxU8ANJbWB5s12Bw8DjRbHVtmc45lNNlD6XPI=)

**Comment by P3p1t0** [comment]
Could it be caused by the fact the new icon isn't actually a square picture?

**Comment by P3p1t0** [comment]
Could it be caused by the fact it isn't a square picture, unlike other icons?

**Comment by P3p1t0** [comment]
It's indeed the problem: XFCE tray doesn't like non-square icon very much.

Creating /scalable/ac-adapter.svg symbolic link to /16x16/ac-adapter-symbolic.svg or even /24x24/ac-adapter-symbolic.svg solved the issue. Here's the result.
16x16-symboliclink
24x24-symboliclink

I created a pull request in order to change the symbolic link to 24x24 :https://github.com/manjaro/vertex-maia-icon-themes/pull/7

**Comment by sdwolf** [comment]
Awesome! Great work ❤️ !

**Pull request merged**
